p8105_hw3_pw2551
================
Paula Wu
10/14/2021

Import the library:

``` r
library(tidyverse)
library(viridis)
```

### Problem 1

Load in dataset

``` r
library(p8105.datasets)
data("instacart")
```

``` r
# it would be easier to store this as a new variable
aisle = 
  instacart %>% 
  group_by(aisle_id) %>% 
  summarize(n_obs = n()) %>% 
  arrange(desc(n_obs))  # arrange in descending order
knitr::kable(aisle[1:10,])
```

| aisle_id |  n_obs |
|---------:|-------:|
|       83 | 150609 |
|       24 | 150473 |
|      123 |  78493 |
|      120 |  55240 |
|       21 |  41699 |
|      115 |  36617 |
|       84 |  32644 |
|      107 |  31269 |
|       91 |  26240 |
|      112 |  23635 |

There are 134 aisles. Aisle number 83 has the most item orders with
150609 observations, followed by aisle number 24 with 150473
observations. <br> <br> Making plots

``` r
aisle %>% 
  filter(n_obs > 10000) %>% 
  ggplot(aes(x = aisle_id, y = n_obs)) +
  geom_point()+
  geom_line()
```

![](p8105_hw3_pw2551_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->
Make a table: best-selling

``` r
table_1 = 
  instacart %>% 
  filter(aisle == c("baking ingredients","dog food care", "packaged vegetables fruits")) %>% 
  group_by(product_name, aisle) %>% 
  summarize(times = n()) %>% 
  arrange(desc(times)) %>% 
  group_by(aisle) %>% 
  top_n(3) %>% 
  select(aisle, everything())
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the `.groups` argument.

    ## Selecting by times

``` r
knitr::kable(table_1)
```

| aisle                      | product_name                                    | times |
|:---------------------------|:------------------------------------------------|------:|
| packaged vegetables fruits | Organic Baby Spinach                            |  3324 |
| packaged vegetables fruits | Organic Raspberries                             |  1920 |
| packaged vegetables fruits | Organic Blueberries                             |  1692 |
| baking ingredients         | Light Brown Sugar                               |   157 |
| baking ingredients         | Pure Baking Soda                                |   140 |
| baking ingredients         | Organic Vanilla Extract                         |   122 |
| dog food care              | Organix Grain Free Chicken & Vegetable Dog Food |    14 |
| dog food care              | Organix Chicken & Brown Rice Recipe             |    13 |
| dog food care              | Original Dry Dog                                |     9 |

Make a table: mean hour

``` r
table_2 = 
  instacart %>% 
  filter(product_name == c("Pink Lady Apples", "Coffee Ice Cream"))
```

    ## Warning in product_name == c("Pink Lady Apples", "Coffee Ice Cream"): longer
    ## object length is not a multiple of shorter object length

``` r
table_2
```

    ## # A tibble: 215 × 15
    ##    order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##       <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ##  1    13887      17334                 4         1  159168 train               5
    ##  2    33963      17334                10         1  180434 train              54
    ##  3    61005       3798                 4         1   76283 train              17
    ##  4    67536       3798                 1         1  162096 train               5
    ##  5    76470       3798                 5         1  180560 train              61
    ##  6    82073       3798                 2         1   76641 train              20
    ##  7    90256       3798                 1         1   39853 train              46
    ##  8   129588       3798                12         0  176433 train              33
    ##  9   134443      17334                 4         0  108799 train              24
    ## 10   163919      17334                 3         1   12058 train               4
    ## # … with 205 more rows, and 8 more variables: order_dow <int>,
    ## #   order_hour_of_day <int>, days_since_prior_order <int>, product_name <chr>,
    ## #   aisle_id <int>, department_id <int>, aisle <chr>, department <chr>
