---
title: "p8105_hw3_pw2551"
author: "Paula Wu"
date: "10/14/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import the library:
```{r, message=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
```

### Problem 1
Load in dataset
```{r}
data("instacart")
```
```{r}
# it would be easier to store this as a new variable
aisle = 
  instacart %>% 
  group_by(aisle_id) %>% 
  summarize(n_obs = n()) %>% 
  arrange(desc(n_obs))  # arrange in descending order
knitr::kable(aisle[1:10,])
```
There are 134 aisles. Aisle number 83 has the most item orders with 150609 observations, followed by aisle number 24 with 150473 observations. <br>
<br> Making plots
```{r}
aisle %>% 
  filter(n_obs > 10000) %>% 
  ggplot(aes(x = aisle_id, y = n_obs)) +
  geom_point()+
  geom_line()
```
Make a table: best-selling
```{r}
table_1 = 
  instacart %>% 
  filter(aisle == c("baking ingredients","dog food care", "packaged vegetables fruits")) %>% 
  group_by(product_name, aisle) %>% 
  summarize(times = n()) %>% 
  arrange(desc(times)) %>% 
  group_by(aisle) %>% 
  top_n(3) %>% 
  unite("products", c(product_name,times), sep = ": ") %>% # for better looking table
  mutate(rank = c(1,2,3)) %>% 
  pivot_wider(names_from = aisle, values_from = products)
knitr::kable(table_1)
```

Make a table: mean hour
```{r}
table_2 = 
  instacart %>% 
  filter(product_name == c("Pink Lady Apples", "Coffee Ice Cream"))
table_2
```

### Problem 2
Load in data set
```{r}
library(p8105.datasets)
data("brfss_smart2010")
```
Data Cleaning
```{r}
brfss = 
  brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health") %>% 
  filter(response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>%
  mutate(response = factor(response, levels = c("Excellent", "Very good", "Good", "Fair", "Poor"))) %>% 
  arrange(desc(response))
brfss
```
2002 vs 2010:
```{r}
brfss %>% 
  filter(year %in% c(2002, 2010)) %>% 
  arrange(year) %>% 
  select(year, locationabbr, locationdesc) %>% 
  group_by(year, locationabbr) %>% 
  summarize(n_obs = n()) %>% 
  filter(n_obs>=7)
```

Data set limited to `Excellent`:
```{r}
excellent = 
  brfss %>% 
  filter(response == "Excellent")
excellent
```




